apiVersion: v1
kind: Pod
metadata:
    name: wordpress1
    labels:
        role: wp
        app: wordpress
spec:
        containers:
            - name: web
              image: bitnami/wordpress:5.8.2-debian-10-r22
              ports:
                - containerPort: 80
            - name: database-server
              image: bitnami/mysql:latest
              env:
                - name: ALLOW_EMPTY_PASSWORD
                  value: "yes"
              ports:
                - containerPort: 3306
        volumes:
          - name: websvr-storage
            emptyDir: {}
